version: "3"

services:
  discordgpt:
    container_name: ${CONTAINER_NAME:-discordgpt}
    image: discordgpt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "npm start"
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OPENAI_KEY: ${OPENAI_KEY}
      CHANNEL_ID: ${CHANNEL_ID}
      AI_DEFAULT_PERSONALITY: ${AI_PERSONALITY:-"You are a friendly person."}
      AI_MODEL: ${AI_MODEL:-"gpt-3.5-turbo"}
